### ISSUE TITLE
sql 都没有啊

### ISSUE THREAD

**Issue by wangfuxu** [ghuan/blog#1]

**Comment by ghuan** [comment]
之前备份的太晚，sql没有，可以按照实体类自己mysql里建表

**Comment by wangfuxu** [comment]
ok




------------------ 原始邮件 ------------------
发件人: "huan.gao"<notifications@github.com>; 
发送时间: 2019年6月12日(星期三) 上午10:41
收件人: "ghuan/blog"<blog@noreply.github.com>; 
抄送: "tew"<1414150963@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [ghuan/blog] sql 都没有啊 (#1)




之前备份的太晚，sql没有，可以按照实体类自己mysql里建表
